//! Shared by the vcod client and server. No windowing, GPU or audio types in here.

pub mod animscript;
pub mod animtree;
pub mod assets;
pub mod bonetrace;
pub mod bsp;
pub mod collision;
pub mod game_dir;
pub mod localize;
pub mod menu;
pub mod mesh;
pub mod movetrace;
pub mod net;
pub mod pk3;
pub mod playerpose;
pub mod pmove;
pub mod props;
pub mod rng;
pub mod shader;
pub mod skeleton;
pub mod testing;
pub mod turretpose;
pub mod vis;
pub mod voicechat;
pub mod weapon;
pub mod weapon_table;
pub mod xanim;
pub mod xmodel;
