//! GENERATED from the netfield tables of cod_lnxded 1.1d
//! (md5 49717db56f6da717545838ce88d4865e) on 2026-08-23. Do not hand-edit.
//!
//! entityStateFields at vaddr 0x080d1760 (59 entries, entity index 10 bits),
//! playerStateFields at 0x080d229c (103 entries), clientState fields at
//! 0x080d2058 (22 entries, client index 6 bits; MSG_WriteDeltaClient at
//! 0x807f758 passes (table, 6, 0x16, writeLeadingBit=1)).
//! Array order is the wire order; never sort or reorder.
//!
//! Re-verify without the extractor, `objdump -d -j .text cod_lnxded`:
//!   0x807f6ad: push $0x80d1760; push $0xa; push $0x3b
//!     MSG_WriteDeltaEntity passing (table, index bits, field count)
//!   0x807e770: lea 0x80d229c(,%eax,4) with cmpl $0x67
//!     inlined playerState delta loop, 12-byte stride over 103 entries

use super::protocol::NetField;

#[rustfmt::skip]
pub static ENTITY_FIELDS: &[NetField] = &[
    NetField { name: "pos.trTime", offset: 16, bits: 32 },
    NetField { name: "pos.trBase[0]", offset: 24, bits: 0 },
    NetField { name: "pos.trBase[1]", offset: 28, bits: 0 },
    NetField { name: "pos.trDelta[1]", offset: 40, bits: 0 },
    NetField { name: "pos.trDelta[0]", offset: 36, bits: 0 },
    NetField { name: "angles2[1]", offset: 108, bits: 0 },
    NetField { name: "apos.trBase[1]", offset: 64, bits: 0 },
    NetField { name: "apos.trBase[0]", offset: 60, bits: 0 },
    NetField { name: "pos.trBase[2]", offset: 32, bits: 0 },
    NetField { name: "pos.trDelta[2]", offset: 44, bits: 0 },
    NetField { name: "eventSequence", offset: 164, bits: 8 },
    NetField { name: "eType", offset: 4, bits: 8 },
    NetField { name: "eFlags", offset: 8, bits: 24 },
    NetField { name: "groundEntityNum", offset: 124, bits: 10 },
    NetField { name: "legsAnim", offset: 204, bits: 10 },
    NetField { name: "clientNum", offset: 144, bits: 8 },
    NetField { name: "apos.trBase[2]", offset: 68, bits: 0 },
    NetField { name: "events[0]", offset: 168, bits: 8 },
    NetField { name: "index", offset: 140, bits: 9 },
    NetField { name: "events[1]", offset: 172, bits: 8 },
    NetField { name: "events[2]", offset: 176, bits: 8 },
    NetField { name: "events[3]", offset: 180, bits: 8 },
    NetField { name: "eventParm", offset: 160, bits: 8 },
    NetField { name: "torsoAnim", offset: 208, bits: 10 },
    NetField { name: "surfType", offset: 136, bits: 8 },
    NetField { name: "_union.scale", offset: 216, bits: 8 },
    NetField { name: "otherEntityNum", offset: 116, bits: 10 },
    NetField { name: "fWaistPitch", offset: 236, bits: 0 },
    NetField { name: "pos.trType", offset: 12, bits: 8 },
    NetField { name: "angles2[0]", offset: 104, bits: 0 },
    NetField { name: "fTorsoHeight", offset: 228, bits: 0 },
    NetField { name: "fTorsoPitch", offset: 232, bits: 0 },
    NetField { name: "apos.trType", offset: 48, bits: 8 },
    NetField { name: "solid", offset: 156, bits: 24 },
    NetField { name: "weapon", offset: 200, bits: 6 },
    NetField { name: "apos.trTime", offset: 52, bits: 32 },
    NetField { name: "apos.trDelta[0]", offset: 72, bits: 0 },
    NetField { name: "eventParms[0]", offset: 184, bits: 8 },
    NetField { name: "pos.trDuration", offset: 20, bits: 32 },
    NetField { name: "animMovetype", offset: 224, bits: 4 },
    NetField { name: "eventParms[1]", offset: 188, bits: 8 },
    NetField { name: "apos.trDelta[2]", offset: 80, bits: 0 },
    NetField { name: "eventParms[2]", offset: 192, bits: 8 },
    NetField { name: "eventParms[3]", offset: 196, bits: 8 },
    NetField { name: "leanf", offset: 212, bits: 0 },
    NetField { name: "apos.trDelta[1]", offset: 76, bits: 0 },
    NetField { name: "loopSound", offset: 132, bits: 8 },
    NetField { name: "attackerEntityNum", offset: 120, bits: 10 },
    NetField { name: "iHeadIcon", offset: 148, bits: 4 },
    NetField { name: "iHeadIconTeam", offset: 152, bits: 2 },
    NetField { name: "apos.trDuration", offset: 56, bits: 32 },
    NetField { name: "time", offset: 84, bits: 32 },
    NetField { name: "time2", offset: 88, bits: 32 },
    NetField { name: "origin2[0]", offset: 92, bits: 0 },
    NetField { name: "origin2[1]", offset: 96, bits: 0 },
    NetField { name: "origin2[2]", offset: 100, bits: 0 },
    NetField { name: "angles2[2]", offset: 112, bits: 0 },
    NetField { name: "constantLight", offset: 128, bits: 32 },
    NetField { name: "dmgFlags", offset: 220, bits: 32 },
];

#[rustfmt::skip]
pub static PLAYER_FIELDS: &[NetField] = &[
    NetField { name: "commandTime", offset: 0, bits: 32 },
    NetField { name: "origin[1]", offset: 24, bits: 0 },
    NetField { name: "origin[0]", offset: 20, bits: 0 },
    NetField { name: "origin[2]", offset: 28, bits: 0 },
    NetField { name: "viewangles[1]", offset: 196, bits: 0 },
    NetField { name: "viewangles[0]", offset: 192, bits: 0 },
    NetField { name: "iCompassFriendInfo", offset: 960, bits: 32 },
    NetField { name: "eFlags", offset: 128, bits: 24 },
    NetField { name: "bobCycle", offset: 8, bits: 8 },
    NetField { name: "viewHeightCurrent", offset: 208, bits: 0 },
    NetField { name: "eventSequence", offset: 132, bits: 8 },
    NetField { name: "legsAnim", offset: 112, bits: 10 },
    NetField { name: "pm_flags", offset: 12, bits: 19 },
    NetField { name: "delta_angles[1]", offset: 76, bits: 16 },
    NetField { name: "velocity[1]", offset: 36, bits: 0 },
    NetField { name: "velocity[0]", offset: 32, bits: 0 },
    NetField { name: "speed", offset: 68, bits: 16 },
    NetField { name: "mins[0]", offset: 804, bits: 0 },
    NetField { name: "mins[1]", offset: 808, bits: 0 },
    NetField { name: "maxs[0]", offset: 816, bits: 0 },
    NetField { name: "maxs[1]", offset: 820, bits: 0 },
    NetField { name: "maxs[2]", offset: 824, bits: 0 },
    NetField { name: "proneViewHeight", offset: 828, bits: -8 },
    NetField { name: "crouchViewHeight", offset: 832, bits: -8 },
    NetField { name: "standViewHeight", offset: 836, bits: -8 },
    NetField { name: "deadViewHeight", offset: 840, bits: -8 },
    NetField { name: "walkSpeedScale", offset: 844, bits: 0 },
    NetField { name: "runSpeedScale", offset: 848, bits: 0 },
    NetField { name: "proneSpeedScale", offset: 852, bits: 0 },
    NetField { name: "crouchSpeedScale", offset: 856, bits: 0 },
    NetField { name: "strafeSpeedScale", offset: 860, bits: 0 },
    NetField { name: "backSpeedScale", offset: 864, bits: 0 },
    NetField { name: "leanSpeedScale", offset: 868, bits: 0 },
    NetField { name: "friction", offset: 892, bits: 0 },
    NetField { name: "groundEntityNum", offset: 84, bits: 10 },
    NetField { name: "viewHeightTarget", offset: 204, bits: -8 },
    NetField { name: "events[0]", offset: 136, bits: 8 },
    NetField { name: "weapons[0]", offset: 780, bits: 32 },
    NetField { name: "weaponslots[0]", offset: 788, bits: 32 },
    NetField { name: "gravity", offset: 60, bits: 16 },
    NetField { name: "serverCursorHintString", offset: 908, bits: -8 },
    NetField { name: "viewmodelIndex", offset: 188, bits: 8 },
    NetField { name: "events[1]", offset: 140, bits: 8 },
    NetField { name: "events[2]", offset: 144, bits: 8 },
    NetField { name: "events[3]", offset: 148, bits: 8 },
    NetField { name: "delta_angles[0]", offset: 72, bits: 16 },
    NetField { name: "weapon", offset: 176, bits: 6 },
    NetField { name: "movementDir", offset: 124, bits: 8 },
    NetField { name: "viewHeightLerpTarget", offset: 216, bits: -8 },
    NetField { name: "weaponslots[4]", offset: 792, bits: 32 },
    NetField { name: "proneDirection", offset: 872, bits: 0 },
    NetField { name: "aimSpreadScale", offset: 984, bits: 0 },
    NetField { name: "weapAnim", offset: 980, bits: 10 },
    NetField { name: "jumpTime", offset: 100, bits: 32 },
    NetField { name: "velocity[2]", offset: 40, bits: 0 },
    NetField { name: "weaponTime", offset: 44, bits: -16 },
    NetField { name: "proneTorsoPitch", offset: 880, bits: 0 },
    NetField { name: "proneDirectionPitch", offset: 876, bits: 0 },
    NetField { name: "fTorsoPitch", offset: 968, bits: 0 },
    NetField { name: "fWaistPitch", offset: 972, bits: 0 },
    NetField { name: "fTorsoHeight", offset: 964, bits: 0 },
    NetField { name: "weaponstate", offset: 180, bits: 4 },
    NetField { name: "torsoTimer", offset: 116, bits: 16 },
    NetField { name: "torsoAnim", offset: 120, bits: 10 },
    NetField { name: "eventParms[0]", offset: 152, bits: 8 },
    NetField { name: "vLadderVec[0]", offset: 88, bits: 0 },
    NetField { name: "eventParms[3]", offset: 164, bits: 8 },
    NetField { name: "viewHeightLerpDown", offset: 220, bits: 1 },
    NetField { name: "weaponDelay", offset: 48, bits: -16 },
    NetField { name: "eventParms[1]", offset: 156, bits: 8 },
    NetField { name: "viewHeightLerpTime", offset: 212, bits: 32 },
    NetField { name: "eventParms[2]", offset: 160, bits: 8 },
    NetField { name: "vLadderVec[1]", offset: 92, bits: 0 },
    NetField { name: "fWeaponPosFrac", offset: 184, bits: 0 },
    NetField { name: "pm_type", offset: 4, bits: 8 },
    NetField { name: "legsTimer", offset: 108, bits: 16 },
    NetField { name: "fJumpPeak", offset: 104, bits: 0 },
    NetField { name: "leanf", offset: 64, bits: 0 },
    NetField { name: "damageEvent", offset: 228, bits: 8 },
    NetField { name: "damageYaw", offset: 232, bits: 8 },
    NetField { name: "damagePitch", offset: 236, bits: 8 },
    NetField { name: "damageCount", offset: 240, bits: 7 },
    NetField { name: "weaponrechamber[0]", offset: 796, bits: 32 },
    NetField { name: "grenadeTimeLeft", offset: 52, bits: -16 },
    NetField { name: "pm_time", offset: 16, bits: -16 },
    NetField { name: "iFoliageSoundTime", offset: 56, bits: 32 },
    NetField { name: "deltaTime", offset: 8396, bits: 32 },
    NetField { name: "serverCursorHint", offset: 900, bits: 8 },
    NetField { name: "serverCursorHintVal", offset: 904, bits: 8 },
    NetField { name: "shellshockIndex", offset: 988, bits: 4 },
    NetField { name: "shellshockTime", offset: 992, bits: 32 },
    NetField { name: "shellshockDuration", offset: 996, bits: 16 },
    NetField { name: "delta_angles[2]", offset: 80, bits: 16 },
    NetField { name: "vLadderVec[2]", offset: 96, bits: 0 },
    NetField { name: "clientNum", offset: 172, bits: 8 },
    NetField { name: "weapons[1]", offset: 784, bits: 32 },
    NetField { name: "weaponrechamber[1]", offset: 800, bits: 32 },
    NetField { name: "viewangles[2]", offset: 200, bits: 0 },
    NetField { name: "viewHeightLerpPosAdj", offset: 224, bits: 0 },
    NetField { name: "mins[2]", offset: 812, bits: 0 },
    NetField { name: "viewlocked", offset: 884, bits: 8 },
    NetField { name: "viewlocked_entNum", offset: 888, bits: 16 },
    NetField { name: "gunfx", offset: 896, bits: 8 },
];

#[rustfmt::skip]
pub static CLIENT_FIELDS: &[NetField] = &[
    NetField { name: "team", offset: 4, bits: 2 },
    NetField { name: "name[0]", offset: 60, bits: 32 },
    NetField { name: "name[4]", offset: 64, bits: 32 },
    NetField { name: "attachModelIndex[0]", offset: 12, bits: 8 },
    NetField { name: "attachModelIndex[2]", offset: 20, bits: 8 },
    NetField { name: "attachModelIndex[3]", offset: 24, bits: 8 },
    NetField { name: "modelindex", offset: 8, bits: 8 },
    NetField { name: "attachModelIndex[1]", offset: 16, bits: 8 },
    NetField { name: "name[8]", offset: 68, bits: 32 },
    NetField { name: "name[12]", offset: 72, bits: 32 },
    NetField { name: "attachModelIndex[4]", offset: 28, bits: 8 },
    NetField { name: "name[16]", offset: 76, bits: 32 },
    NetField { name: "attachTagIndex[0]", offset: 36, bits: 5 },
    NetField { name: "attachTagIndex[1]", offset: 40, bits: 5 },
    NetField { name: "attachTagIndex[2]", offset: 44, bits: 5 },
    NetField { name: "attachTagIndex[3]", offset: 48, bits: 5 },
    NetField { name: "attachTagIndex[4]", offset: 52, bits: 5 },
    NetField { name: "attachModelIndex[5]", offset: 32, bits: 8 },
    NetField { name: "attachTagIndex[5]", offset: 56, bits: 5 },
    NetField { name: "name[20]", offset: 80, bits: 32 },
    NetField { name: "name[24]", offset: 84, bits: 32 },
    NetField { name: "name[28]", offset: 88, bits: 32 },
];
