[package]
name = "vcod-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
publish = false
description = "Call of Duty (2003) 1.1 dedicated server, in progress"

[dependencies]
vcod-common.workspace = true
vcod-gsc.workspace = true
anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
log.workspace = true
glam.workspace = true
